# ============================================================================
# SingleStore EMBED_TEXT Demo - Direct Ingestion (No Kafka)
# ============================================================================

services:
  hn-fetcher-direct:
    build:
      context: ./fetcher
      dockerfile: Dockerfile
    container_name: singlestore-hn-fetcher-direct
    command: python hn_fetcher_direct.py
    environment:
      SINGLESTORE_HOST: ${SINGLESTORE_HOST}
      SINGLESTORE_PORT: ${SINGLESTORE_PORT:-3306}
      SINGLESTORE_USER: ${SINGLESTORE_USER}
      SINGLESTORE_PASSWORD: ${SINGLESTORE_PASSWORD}
      SINGLESTORE_DATABASE: ${SINGLESTORE_DATABASE:-hackernews_semantic}
      HN_FETCH_INTERVAL_SECONDS: ${HN_FETCH_INTERVAL_SECONDS:-30}
      HN_MAX_STORIES_PER_FETCH: ${HN_MAX_STORIES_PER_FETCH:-10}
      HN_MAX_COMMENTS_PER_STORY: ${HN_MAX_COMMENTS_PER_STORY:-20}
      HN_ENABLE_STORIES: ${HN_ENABLE_STORIES:-true}
      HN_ENABLE_COMMENTS: ${HN_ENABLE_COMMENTS:-true}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ./fetcher:/app
    restart: unless-stopped
